package com.example.visionwidget.data

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.Transaction
import kotlinx.coroutines.flow.Flow

/**
 * One of Today's three slots. [slotIndex] (0–2) is the primary key rather than an
 * autogenerated id — there are only ever three, and each always means the same
 * position in the list, so it doubles as its own identity.
 */
@Entity(tableName = "rule_of_three_slots")
data class RuleOfThreeSlotEntity(
    @PrimaryKey val slotIndex: Int,
    val task: String?,
    val checked: Boolean
)

/**
 * Which day [RuleOfThreeSlotEntity] currently represents — a single row, so the
 * DAO can tell a fresh day has started and the live slots need rolling over.
 */
@Entity(tableName = "rule_of_three_state")
data class RuleOfThreeStateEntity(
    @PrimaryKey val id: Int = 0,
    val date: Long
)

/**
 * A slot as it stood at the end of a day that's since passed. Nothing reads this yet —
 * it's laid down so a past-days tab can later show what was set and what got checked.
 */
@Entity(tableName = "rule_of_three_history", primaryKeys = ["date", "slotIndex"])
data class RuleOfThreeHistoryEntity(
    val date: Long,
    val slotIndex: Int,
    val task: String?,
    val checked: Boolean
)

@Dao
interface RuleOfThreeDao {
    @Query("SELECT * FROM rule_of_three_slots ORDER BY slotIndex")
    fun observeSlots(): Flow<List<RuleOfThreeSlotEntity>>

    /** A slot with no row yet reads the same as an empty, unchecked one. */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun upsert(slot: RuleOfThreeSlotEntity)

    @Query("SELECT * FROM rule_of_three_slots")
    suspend fun currentSlots(): List<RuleOfThreeSlotEntity>

    @Query("SELECT date FROM rule_of_three_state WHERE id = 0")
    suspend fun liveDate(): Long?

    /** The live day, watched — Insights reads it to date the slots that aren't archived yet. */
    @Query("SELECT date FROM rule_of_three_state WHERE id = 0")
    fun observeLiveDate(): Flow<Long?>

    /**
     * Every archived day at once. Three rows a day keeps this small enough that paging
     * would cost more than it saves, and the all-time stats need the whole set anyway.
     */
    @Query("SELECT * FROM rule_of_three_history ORDER BY date DESC, slotIndex")
    fun observeHistory(): Flow<List<RuleOfThreeHistoryEntity>>

    /** Ticking a past day off from Insights, long after it was archived. */
    @Query("UPDATE rule_of_three_history SET checked = NOT checked WHERE date = :date AND slotIndex = :slotIndex")
    suspend fun toggleHistory(date: Long, slotIndex: Int)

    /** The same gesture on the live day, which has no history row yet. */
    @Query("UPDATE rule_of_three_slots SET checked = NOT checked WHERE slotIndex = :slotIndex")
    suspend fun toggleSlot(slotIndex: Int)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun setLiveDate(state: RuleOfThreeStateEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun archive(entries: List<RuleOfThreeHistoryEntity>)

    @Query("DELETE FROM rule_of_three_slots")
    suspend fun clearSlots()

    /**
     * Called once per app start. If the live slots still belong to an earlier day and
     * at least one holds a task, that day is archived before the slots are cleared for
     * today — an empty day leaves nothing worth keeping, so it's just dated forward.
     */
    @Transaction
    suspend fun rolloverToToday(today: Long) {
        val lastDate = liveDate()
        if (lastDate != null && lastDate != today) {
            val slots = currentSlots()
            if (slots.any { it.task != null }) {
                archive(slots.map { RuleOfThreeHistoryEntity(lastDate, it.slotIndex, it.task, it.checked) })
            }
            clearSlots()
        }
        setLiveDate(RuleOfThreeStateEntity(date = today))
    }
}
